### ISSUE TITLE
What I am doing wrong

### ISSUE THREAD

**Issue by ignatandrei** [svee4/RequiredStaticMembers#4]
I am maintaining a list of Roslyn Code Generators at https://ignatandrei.github.io/RSCG_Examples/v2/docs/List-of-RSCG 

I want to add you example, but unfortunately it does not give me an error
Please see attached project
[src.zip](https://github.com/user-attachments/files/18239633/src.zip)

**Comment by svee4** [comment]
hi, honestly this project is dead and will be indefinitely unless i find a usecase for it. theres probably bugs hiding, as it never reached 1.0 release.
